imports:
    - { resource: tables.yml }

services:
    phpbb.ideas.listener:
        class: phpbb\ideas\event\listener
        arguments:
            - @auth
            - @config
            - @controller.helper
            - @phpbb.ideas.ideas
            - @phpbb.ideas.linkhelper
            - @template
            - @user
        tags:
            - { name: event.listener }

    phpbb.ideas.controller.base:
        abstract: true
        arguments:
            - @config
            - @controller.helper
            - @phpbb.ideas.ideas
            - @language
            - @phpbb.ideas.linkhelper
            - @request
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%

    phpbb.ideas.index_controller:
        class: phpbb\ideas\controller\index_controller
        parent: phpbb.ideas.controller.base

    phpbb.ideas.list_controller:
        class: phpbb\ideas\controller\list_controller
        parent: phpbb.ideas.controller.base

    phpbb.ideas.post_controller:
        class: phpbb\ideas\controller\post_controller
        parent: phpbb.ideas.controller.base

    phpbb.ideas.idea_controller:
        class: phpbb\ideas\controller\idea_controller
        arguments:
            - @auth
            - @config
            - @controller.helper
            - @phpbb.ideas.ideas
            - @language
            - @phpbb.ideas.linkhelper
            - @request
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%

    phpbb.ideas.ideas:
        class: phpbb\ideas\factory\ideas
        arguments:
            - @config
            - @dbal.conn
            - @controller.helper
            - @language
            - @log
            - @user
            - %tables.ideas_ideas%
            - %tables.ideas_duplicates%
            - %tables.ideas_rfcs%
            - %tables.ideas_statuses%
            - %tables.ideas_tickets%
            - %tables.ideas_votes%
            - %core.php_ext%

    phpbb.ideas.linkhelper:
        class: phpbb\ideas\factory\linkhelper
        arguments:
            - @controller.helper
            - @user_loader
