imports:
    - { resource: tables.yml }

services:
    phpbb.ideas.listener:
        class: phpbb\ideas\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@phpbb.ideas.ideas'
            - '@language'
            - '@phpbb.ideas.linkhelper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    phpbb.ideas.admin.controller:
        class: phpbb\ideas\controller\admin_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbb.ideas.controller.base:
        abstract: true
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@phpbb.ideas.ideas'
            - '@language'
            - '@phpbb.ideas.linkhelper'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    phpbb.ideas.index_controller:
        class: phpbb\ideas\controller\index_controller
        parent: phpbb.ideas.controller.base

    phpbb.ideas.list_controller:
        class: phpbb\ideas\controller\list_controller
        parent: phpbb.ideas.controller.base

    phpbb.ideas.post_controller:
        class: phpbb\ideas\controller\post_controller
        parent: phpbb.ideas.controller.base

    phpbb.ideas.idea_controller:
        class: phpbb\ideas\controller\idea_controller
        parent: phpbb.ideas.controller.base

    phpbb.ideas.ideas:
        class: phpbb\ideas\factory\ideas
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '%tables.ideas_ideas%'
            - '%tables.ideas_votes%'
            - '%tables.topics%'
            - '%core.php_ext%'

    phpbb.ideas.linkhelper:
        class: phpbb\ideas\factory\linkhelper
        arguments:
            - '@controller.helper'
            - '@user_loader'

    phpbb.ideas.twig.extension.ideas_status_icon:
        class: phpbb\ideas\template\twig\extension\ideas_status_icon
        tags:
            - { name: twig.extension }

# ----- Cron tasks -----
    phpbb.ideas.cron.task.prune_orphaned_ideas:
        class: phpbb\ideas\cron\prune_orphaned_ideas
        arguments:
            - '@config'
            - '@phpbb.ideas.ideas'
        calls:
            - [set_name, [cron.task.prune_orphaned_ideas]]
        tags:
            - { name: cron.task }
